Repository DevQoo/devqoo-backend, pull requests merged in 2025-05, with the labels that each got.

#32 ci: Gradle CI 워크플로 추가로 main·develop 병합 전 빌드 검증
  .github/workflows/build-check.yml
Labels: ⚙ Setting

#34 CI-flow에 필요한 test 환경 구성
  src/main/java/com/devqoo/backend/common/exception/CommonExceptionHandler.java
  src/main/resources/application-test.yml
Labels: ⚙ Setting

#41 Feat: commonResponse 생성
  build.gradle
  src/main/java/com/devqoo/backend/category/entity/Category.java
  src/main/java/com/devqoo/backend/common/exception/CommonExceptionHandler.java
  src/main/java/com/devqoo/backend/common/exception/ErrorCode.java
  src/main/java/com/devqoo/backend/common/response/CommonResponse.java
Labels: ✨ Feature

#47 #13 카테고리 API 작성 + Swagger API 인터페이스 설정
  src/main/java/com/devqoo/backend/category/controller/CategoryApiDocs.java
  src/main/java/com/devqoo/backend/category/controller/CategoryController.java
  src/main/java/com/devqoo/backend/category/dto/form/RegisterCategoryForm.java
  src/main/java/com/devqoo/backend/category/dto/response/CategoryResponseDto.java
  src/main/java/com/devqoo/backend/category/entity/Category.java
  src/main/java/com/devqoo/backend/common/response/CommonResponse.java
Labels: ✨ Feature, 📬 API

#49 Feat: business exception 추가
  src/main/java/com/devqoo/backend/common/exception/BusinessException.java
  src/main/java/com/devqoo/backend/common/exception/CommonExceptionHandler.java
  src/main/java/com/devqoo/backend/common/exception/ErrorCode.java
  src/main/java/com/devqoo/backend/common/response/CommonResponse.java
  src/test/java/com/devqoo/backend/post/controller/PostControllerTest.java
Labels: ✨ Feature

#50 ✨ Feat 카테고리 전체 조회 기능 추가
  src/main/java/com/devqoo/backend/category/controller/CategoryApiDocs.java
  src/main/java/com/devqoo/backend/category/controller/CategoryController.java
  src/main/java/com/devqoo/backend/category/service/CategoryFacade.java
  src/main/java/com/devqoo/backend/category/service/CategoryService.java
  src/test/java/com/devqoo/backend/category/repository/CategoryRepositoryTest.java
  src/test/java/com/devqoo/backend/category/service/CategoryServiceTest.java
Labels: ✨ Feature

#51 Feat : Jwt 초기 생성
  build.gradle
  src/main/java/com/devqoo/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devqoo/backend/auth/jwt/JwtProvider.java
  src/main/java/com/devqoo/backend/auth/jwt/SecretKeyType.java
  src/main/java/com/devqoo/backend/auth/security/CustomUserDetails.java
  src/main/java/com/devqoo/backend/common/exception/ErrorCode.java
  src/main/resources/application-jwt.yaml
  src/test/java/com/devqoo/backend/auth/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/devqoo/backend/auth/jwt/JwtProviderTest.java
  src/test/java/com/devqoo/backend/category/controller/CategoryControllerTest.java
  src/test/java/com/devqoo/backend/post/controller/PostControllerTest.java
Labels: ✨ Feature

#52 Feat: 게시글 상세 조회
  src/main/java/com/devqoo/backend/category/service/CategoryService.java
  src/main/java/com/devqoo/backend/common/exception/ErrorCode.java
  src/main/java/com/devqoo/backend/post/controller/PostApiDocs.java
  src/main/java/com/devqoo/backend/post/controller/PostController.java
  src/main/java/com/devqoo/backend/post/dto/response/PostResponseDto.java
  src/main/java/com/devqoo/backend/post/service/PostFacade.java
  src/main/java/com/devqoo/backend/post/service/PostService.java
  src/main/java/com/devqoo/backend/user/service/UserService.java
Labels: ✨ Feature

#53 카테고리 수정 MVC 기능 구현
  src/main/java/com/devqoo/backend/category/controller/CategoryApiDocs.java
  src/main/java/com/devqoo/backend/category/controller/CategoryController.java
  src/main/java/com/devqoo/backend/category/entity/Category.java
  src/main/java/com/devqoo/backend/category/service/CategoryFacade.java
  src/main/java/com/devqoo/backend/category/service/CategoryService.java
  src/test/java/com/devqoo/backend/category/controller/CategoryControllerTest.java
  src/test/java/com/devqoo/backend/category/service/CategoryServiceTest.java
Labels: ✨ Feature

#54 Test Category 수정 MVC 테스트
  src/main/java/com/devqoo/backend/category/service/CategoryService.java
  src/test/java/com/devqoo/backend/category/controller/CategoryControllerTest.java
  src/test/java/com/devqoo/backend/category/service/CategoryServiceTest.java
Labels: ✅ Test

#55 카테고리 삭제 MVC 구조 기능 구현
  src/main/java/com/devqoo/backend/category/controller/CategoryController.java
  src/main/java/com/devqoo/backend/category/service/CategoryFacade.java
  src/main/java/com/devqoo/backend/category/service/CategoryService.java
Labels: ✨ Feature

#56 Feat: 게시글 수정 기능 구현
  src/main/java/com/devqoo/backend/post/controller/PostApiDocs.java
  src/main/java/com/devqoo/backend/post/controller/PostController.java
  src/main/java/com/devqoo/backend/post/dto/form/PostForm.java
  src/main/java/com/devqoo/backend/post/entity/Post.java
  src/main/java/com/devqoo/backend/post/repository/PostRepository.java
  src/main/java/com/devqoo/backend/post/service/PostFacade.java
  src/main/java/com/devqoo/backend/post/service/PostService.java
  src/main/resources/application-dev.yaml
Labels: ✨ Feature

#58 Feat: 회원가입 기능 추가
  src/main/java/com/devqoo/backend/auth/jwt/JwtProvider.java
  src/main/java/com/devqoo/backend/common/config/SecurityConfig.java
  src/main/java/com/devqoo/backend/common/exception/ErrorCode.java
  src/main/java/com/devqoo/backend/user/controller/UserApiDocs.java
  src/main/java/com/devqoo/backend/user/controller/UserController.java
  src/main/java/com/devqoo/backend/user/dto/form/SignUpForm.java
  src/main/java/com/devqoo/backend/user/entity/User.java
  src/main/java/com/devqoo/backend/user/enums/UserRoleType.java
  src/main/java/com/devqoo/backend/user/repository/UserRepository.java
  src/main/java/com/devqoo/backend/user/service/UserService.java
  src/main/java/com/devqoo/backend/user/validation/PasswordMatches.java
  src/main/java/com/devqoo/backend/user/validation/PasswordMatchesValidator.java
  src/main/java/com/devqoo/backend/user/validation/PasswordPolicy.java
  src/main/java/com/devqoo/backend/user/validation/PasswordPolicyValidator.java
  src/test/java/com/devqoo/backend/user/service/UserServiceTest.java
Labels: ✨ Feature
